[workspace]
authors = ["Bruno Mazzotti <bruno.mazzotti@amd.com>"]
channels = ["https://conda.modular.com/max-nightly", "conda-forge"]
name = "mojo"
platforms = ["linux-64"]
version = "0.0.0"

[dependencies]
modular = ">=25.6.0.dev2025073007,<26"
